[project]
name = "youtube-thumbnails"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "feedparser>=6.0.11",
    "pillow>=11.3.0",
    "python-dotenv>=1.1.1",
]
